### ISSUE TITLE
Deployment tool | /etc/default/apport' does NOT exist

### ISSUE THREAD

**Issue by WayneWayner** [KiraCore/kira#9]
Got following exception during quick setup:

```
Executing command: 'text lineswap' Named Arguments: 
{
  "insert": "enabled=0",
  "prefix": "enabled=",
  "path": "/etc/default/apport",
  "append-if-found-not": "True"
}


[2020-12-31 16:46:18.664] Failure, Error Message: {
  "StackTrace": [
    "C:\\Users\\asmodat\\Documents\\Visual Studio 2017\\Projects\\Asmodat-Standard\\Asmodat Standard\\Extensions\\Helpers\\FileHelper.cs => IsDirectory() l:98 c:13",
    "C:\\Users\\asmodat\\Documents\\Visual Studio 2017\\Projects\\Asmodat-Standard\\Asmodat Standard\\Extensions\\Helpers\\FileHelper.cs => GetFiles() l:22 c:13",
    "C:\\Users\\asmodat\\Documents\\Visual Studio 2017\\Projects\\Asmodat-Standard\\Asmodat Standard\\Extensions\\Helpers\\FileHelper.cs => GetFiles() l:32 c:21",
    "C:\\Users\\asmodat\\Documents\\Visual Studio 2017\\Projects\\CDHelper\\CDHelper\\Execute\\text.cs => executeText() l:97 c:25",
    "C:\\Users\\asmodat\\Documents\\Visual Studio 2017\\Projects\\CDHelper\\CDHelper\\Program.cs => MoveNext() l:174 c:21",
    " => ThrowForNonSuccess() l:0 c:0",
    "C:\\Users\\asmodat\\Documents\\Visual Studio 2017\\Projects\\CDHelper\\CDHelper\\Program.cs => MoveNext() l:121 c:21"
  ],
  "Type": "System.Exception",
  "Message": "DIRECTORY or File '/etc/default/apport' does NOT exist."
}
Unhandled exception. System.Exception: CDHelper v0.6.15 failed during execution of text command.
   at CDHelper.Program.Main(String[] args)
   at CDHelper.Program.<Main>(String[] args)
/kira/manager/setup/envs.sh: line 142:  8848 Aborted                 CDHelper text lineswap --insert="enabled=0" --prefix="enabled=" --path=/etc/default/apport --append-if-found-not=True
ERROR: Failed to launch the infrastructure
```

**Hot fix:** 
create an empty file as root `touch /etc/default/apport`
Later in the setup you will then be asked to replace this self created file which you confirm.

**Comment by asmodat** [comment]
Hotfix applied to dev branch, thank you
